### ISSUE TITLE
How to make this work with redmine_project_specific_email_sender

### ISSUE THREAD

**Issue by flantel** [gyselroth/redmine-plugin-autorespond#1]
Hi

Thanks for this plugin, it is nice and simple. One issue I have found - I use the plugin  at https://github.com/joaquinromero/redmine_project_specific_email_sender.git so that each project can have its own From address. Works fine, except with autoresponder, which always sends form the global Emission sender.

I know this is likely not an issue on your end, but my Ruby is (severely) limited and I wonder where I should change so that autorespond can use the pre-project Emission address?

Thanks

-Barry

**Comment by juckerf** [comment]
Hi Barry

Nice to see that this plugin is used by others :-)

Regarding to your question: hm.. I think there would be several ways to make these plugins work together (although my ruby is limited too). But I have to think them through to find a clean way for this (keeping the plugin general and without risking to interfere too much with other plugins).

If you - despite your limited ruby knowledge - have developed some solution for this, feel free to make a PR

**Comment by flantel** [comment]
If I figure out a way I'll be sure to let you know!

**Comment by flantel** [comment]
OK, got it working. In lib/autorespond_mailer_patch.rb I added a line at line 14:

redmine_headers 'Project-Specific-Sender' => issue.project.email if issue.project.email

Which will add the header that the other module picks up in order to change the From address.

Probably of no use to anyone else, but still.
