### ISSUE TITLE
Can't configure the plugin

### ISSUE THREAD

**Issue by MagicFab** [gyselroth/redmine-plugin-autorespond#2]
After installation when clicking on "configure" from the Administration > Plugins list, Redmine returns a 404 error: "The page you were trying to access doesn't exist or has been removed.".

How can the email settings be configured ? Is there a template for subject / body of the autoresponse ?

**Comment by MagicFab** [comment]
As it turns out renaming the plugin directory to "autorespond" and re-deploying made the config page available again.

**Comment by juckerf** [comment]
thanks for the issue and the solution. I will mention it in the readme
